steps:
- name: 'node:latest'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    npm install
    npm run build
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-f'
  - 'Dockerfile'
  - '-t'
  - 'gcr.io/$PROJECT_ID/$IMAGE_NAME:$TAG_NUMBER'
  - '.'
images:
- 'gcr.io/$PROJECT_ID/$IMAGE_NAME:$TAG_NUMBER'
options:
  logging: CLOUD_LOGGING_ONLY
